# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '汽车资讯' do

pod 'AFNetworking'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'


end

target '汽车资讯Tests' do

end

target '汽车资讯UITests' do

end

